import React, { useState, useEffect } from "react";
import { X, Upload, MapPin, Sparkles, Check, AlertTriangle, ShieldCheck, Loader2 } from "lucide-react";
import { Report, IssueCategory, IssueSeverity, UserProfile } from "../types";

interface ReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (report: Omit<Report, "id" | "createdAt" | "updatedAt" | "upvoteCount" | "upvotedBy" | "comments">) => void;
  clickedCoords: { lat: number; lng: number; address: string } | null;
  currentUser: UserProfile;
}

// Beautiful preset high-res incident images for easy, quick browser testing
const PRESET_INCIDENTS = [
  {
    name: "Deep Pothole",
    category: "Pothole" as IssueCategory,
    imageUrl: "https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&w=800&q=80"
  },
  {
    name: "Bursting Water Leak",
    category: "Water Leakage" as IssueCategory,
    imageUrl: "https://images.unsplash.com/photo-1542044896530-05d85be9b11a?auto=format&fit=crop&w=800&q=80"
  },
  {
    name: "Flickering Streetlight",
    category: "Broken Streetlight" as IssueCategory,
    imageUrl: "https://images.unsplash.com/photo-1509024644558-2f56ce76c490?auto=format&fit=crop&w=800&q=80"
  },
  {
    name: "Illegal Waste Dump",
    category: "Waste Management" as IssueCategory,
    imageUrl: "https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80"
  }
];

// Robust helper to compress high-resolution images down to standard web dimensions and size
const compressImage = (base64Str: string, maxWidth = 1200, maxQuality = 0.8): Promise<string> => {
  return new Promise((resolve) => {
    const img = new Image();
    img.src = base64Str;
    img.onload = () => {
      let width = img.width;
      let height = img.height;

      if (width > maxWidth) {
        height = Math.round((height * maxWidth) / width);
        width = maxWidth;
      }

      const canvas = document.createElement("canvas");
      canvas.width = width;
      canvas.height = height;

      const ctx = canvas.getContext("2d");
      if (ctx) {
        ctx.drawImage(img, 0, 0, width, height);
        // Compress as jpeg with high-quality and low byte footprints
        const compressedBase64 = canvas.toDataURL("image/jpeg", maxQuality);
        resolve(compressedBase64);
      } else {
        resolve(base64Str);
      }
    };
    img.onerror = () => {
      resolve(base64Str);
    };
  });
};

export default function ReportModal({ isOpen, onClose, onSubmit, clickedCoords, currentUser }: ReportModalProps) {
  const [selectedImage, setSelectedImage] = useState<string>("");
  const [address, setAddress] = useState<string>("");
  const [latitude, setLatitude] = useState<number>(37.7749);
  const [longitude, setLongitude] = useState<number>(-122.4194);

  // Form states generated by AI analysis
  const [title, setTitle] = useState<string>("");
  const [description, setDescription] = useState<string>("");
  const [category, setCategory] = useState<IssueCategory>("Pothole");
  const [severity, setSeverity] = useState<IssueSeverity>("Medium");
  const [aiCautionTips, setAiCautionTips] = useState<string>("");

  // UI Status states
  const [isAnalyzing, setIsAnalyzing] = useState<boolean>(false);
  const [analysisStep, setAnalysisStep] = useState<string>("");
  const [isAnalyzed, setIsAnalyzed] = useState<boolean>(false);
  const [isDemoAnalysis, setIsDemoAnalysis] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string>("");
  const [isDraggingOver, setIsDraggingOver] = useState<boolean>(false);

  // Sync coords if user clicked on the map canvas
  useEffect(() => {
    if (clickedCoords) {
      setLatitude(clickedCoords.lat);
      setLongitude(clickedCoords.lng);
      setAddress(clickedCoords.address);
    }
  }, [clickedCoords]);

  if (!isOpen) return null;

  // Converts standard image URLs into base64 to transmit to our server-side Gemini API Proxy safely
  const convertUrlToBase64 = async (url: string): Promise<string> => {
    const response = await fetch(url);
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => {
        const base64String = reader.result as string;
        // Strip out metadata header like "data:image/jpeg;base64,"
        const base64Data = base64String.split(",")[1];
        resolve(base64Data);
      };
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  };

  const handlePresetSelect = async (presetUrl: string) => {
    setSelectedImage(presetUrl);
    setErrorMessage("");
    setIsAnalyzed(false);
    triggerAiAnalysis(presetUrl);
  };

  // Unified file processing with automatic client-side image compression
  const processFile = (file: File) => {
    if (!file.type.startsWith("image/")) {
      setErrorMessage("Only image files are supported.");
      return;
    }
    const reader = new FileReader();
    reader.onloadend = async () => {
      const base64Url = reader.result as string;
      setErrorMessage("");
      setIsAnalyzed(false);
      setIsAnalyzing(true);
      setAnalysisStep("Compressing high-resolution asset client-side...");

      try {
        const compressedUrl = await compressImage(base64Url);
        setSelectedImage(compressedUrl);
        triggerAiAnalysis(compressedUrl);
      } catch (err) {
        console.error("Compression error, utilizing fallback raw encoding:", err);
        setSelectedImage(base64Url);
        triggerAiAnalysis(base64Url);
      }
    };
    reader.readAsDataURL(file);
  };

  // Handle local file uploads via file inputs
  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      processFile(file);
    }
  };

  // Handle drag over container
  const handleDragOver = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    if (!isAnalyzing) {
      setIsDraggingOver(true);
    }
  };

  // Handle drag leave container
  const handleDragLeave = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDraggingOver(false);
  };

  // Handle file drop
  const handleDrop = (e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDraggingOver(false);
    if (isAnalyzing) return;
    const file = e.dataTransfer.files?.[0];
    if (file) {
      processFile(file);
    }
  };

  const triggerAiAnalysis = async (imgSource: string) => {
    setIsAnalyzing(true);
    setAnalysisStep("Transmitting image to server-side proxy...");

    try {
      let base64Payload = "";
      if (imgSource.startsWith("http")) {
        setAnalysisStep("Fetching remote image asset...");
        base64Payload = await convertUrlToBase64(imgSource);
      } else {
        base64Payload = imgSource.split(",")[1];
      }

      setAnalysisStep("Analyzing structural layers with Gemini-3.5-Flash...");
      // Introduce subtle delay to let the beautiful scan UI breathe
      await new Promise(r => setTimeout(r, 1000));
      setAnalysisStep("Extracting categorization and severity metrics...");

      const response = await fetch("/api/reports/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          image: base64Payload,
          mimeType: "image/jpeg"
        })
      });

      if (!response.ok) {
        throw new Error(`HTTP Error: ${response.status}`);
      }

      const data = await response.json();
      setAnalysisStep("Completing analysis report...");
      await new Promise(r => setTimeout(r, 600));

      setCategory(data.category);
      setSeverity(data.severity);
      setDescription(data.description);
      setAiCautionTips(data.cautionTips);
      setIsDemoAnalysis(!!data.isDemo);

      // Create a nice automated title based on the category and severity
      setTitle(`Active ${data.severity} ${data.category} Incident`);
      setIsAnalyzed(true);
    } catch (err: any) {
      console.error(err);
      setErrorMessage("Gemini AI was unable to verify this image. Please supply a valid file or check your server configuration.");
    } finally {
      setIsAnalyzing(false);
      setAnalysisStep("");
    }
  };

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedImage) {
      setErrorMessage("Please upload or select an incident photo first.");
      return;
    }
    if (!address.trim()) {
      setErrorMessage("Please specify the street location.");
      return;
    }

    onSubmit({
      reporterId: currentUser.uid,
      reporterName: currentUser.displayName,
      title: title || `${severity} ${category} Alert`,
      description: description || "No detailed description supplied.",
      category,
      severity,
      imageUrl: selectedImage,
      lat: latitude,
      lng: longitude,
      formattedAddress: address,
      status: "reported",
      aiCautionTips: aiCautionTips || "Keep caution when approaching local infrastructure hazards."
    });

    // Reset Form
    setSelectedImage("");
    setTitle("");
    setDescription("");
    setAiCautionTips("");
    setIsAnalyzed(false);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-fade-in">
      <div className="bg-card-bg text-text-main rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto flex flex-col border border-border-color">
        
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-border-color bg-canvas-bg/50">
          <div className="flex items-center gap-2">
            <div className="p-1.5 bg-brand-100 rounded-lg text-brand-700">
              <Sparkles className="w-5 h-5 animate-pulse" />
            </div>
            <div>
              <h3 className="text-base font-bold text-text-main font-sans tracking-tight">Report Local Incident</h3>
              <p className="text-xs text-text-muted">Autonomous Gemini vision classifies and validates your issue instantly.</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1.5 hover:bg-card-hover rounded-lg text-text-muted hover:text-text-main transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body */}
        <form onSubmit={handleFormSubmit} className="p-6 flex-1 space-y-6">

          {/* Preset Picker for Quick Tests */}
          <div>
            <span className="block text-xs font-semibold text-text-muted mb-2.5 uppercase tracking-wider">PRESET INCIDENT SIMULATORS (Recommend for fast testing)</span>
            <div className="grid grid-cols-4 gap-2.5">
              {PRESET_INCIDENTS.map((preset, index) => (
                <button
                  type="button"
                  key={index}
                  onClick={() => handlePresetSelect(preset.imageUrl)}
                  disabled={isAnalyzing}
                  className={`relative h-20 rounded-xl overflow-hidden border-2 text-left transition-all hover:scale-[1.03] active:scale-95 ${
                    selectedImage === preset.imageUrl ? "border-brand-500 ring-2 ring-brand-100" : "border-border-color"
                  }`}
                >
                  <img src={preset.imageUrl} alt={preset.name} className="w-full h-full object-cover" />
                  <div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 to-transparent flex items-end p-2">
                    <span className="text-[10px] font-bold text-white leading-tight">{preset.name}</span>
                  </div>
                  {selectedImage === preset.imageUrl && (
                    <div className="absolute top-1.5 right-1.5 bg-brand-500 text-white rounded-full p-0.5">
                      <Check className="w-3 h-3" />
                    </div>
                  )}
                </button>
              ))}
            </div>
          </div>

          {/* Upload Area */}
          <div className="relative">
            <div
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
              onDrop={handleDrop}
              className={`border-2 border-dashed rounded-2xl p-6 text-center transition-all ${
                isDraggingOver
                  ? "border-brand-500 bg-brand-50/40 scale-[1.01] shadow-md"
                  : selectedImage
                  ? "border-brand-500 bg-brand-50/20"
                  : "border-border-color hover:border-brand-400 bg-canvas-bg/50"
              }`}
            >
              <input
                type="file"
                id="file-uploader"
                accept="image/*"
                onChange={handleFileUpload}
                disabled={isAnalyzing}
                className="hidden"
              />
              <label htmlFor="file-uploader" className="cursor-pointer flex flex-col items-center gap-2">
                <Upload className={`w-8 h-8 transition-transform duration-200 ${isDraggingOver ? "scale-110 text-brand-600" : "text-text-muted hover:text-text-main"}`} />
                <span className="text-xs font-bold text-text-main">
                  {isDraggingOver ? "Drop file now!" : "Drag & Drop or Click to Upload custom image"}
                </span>
                <span className="text-[10px] text-text-muted">Supports JPEG, PNG up to 10MB</span>
              </label>
            </div>
          </div>

          {/* AI Analyzing Radar HUD Overlay */}
          {isAnalyzing && (
            <div className="bg-gradient-to-r from-slate-900 to-slate-950 text-white rounded-xl p-5 border border-slate-800 shadow-inner relative overflow-hidden">
              <div className="flex items-center gap-4 relative z-10">
                <Loader2 className="w-7 h-7 text-brand-400 animate-spin shrink-0" />
                <div className="flex-1">
                  <div className="flex justify-between items-center mb-1">
                    <span className="text-xs font-bold tracking-wider text-brand-400 uppercase flex items-center gap-1.5">
                      <Sparkles className="w-3.5 h-3.5" />
                      Gemini Auto-Analysis HUD
                    </span>
                    <span className="text-[10px] font-mono text-slate-400">STATUS: SCANNING</span>
                  </div>
                  <p className="text-xs text-slate-200 font-medium animate-pulse">{analysisStep}</p>
                </div>
              </div>
              {/* Futuristic scanning light bar effect */}
              <div className="absolute bottom-0 left-0 w-full h-1.5 bg-slate-800">
                <div className="h-full bg-gradient-to-r from-brand-500 to-brand-400 w-1/3 rounded-full animate-[shimmer_2s_infinite]"></div>
              </div>
            </div>
          )}

          {/* AI Analysis Result Form Fields */}
          {isAnalyzed && (
            <div className="bg-brand-50/40 rounded-2xl p-5 border border-brand-100/80 space-y-4 animate-fade-in">
              <div className="flex items-center justify-between border-b border-brand-100 pb-3">
                <span className="text-xs font-bold text-brand-800 flex items-center gap-1.5">
                  <ShieldCheck className="w-4 h-4 text-brand-600" />
                  Gemini Validation Passed Successfully
                </span>
                {isDemoAnalysis && (
                  <span className="text-[9px] font-mono bg-amber-100 text-amber-800 border border-amber-200 px-2 py-0.5 rounded-full font-bold">
                    PRE-KEY DEMO MODE
                  </span>
                )}
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-[10px] font-bold text-slate-600 uppercase mb-1">AI Identified Category</label>
                  <select
                    value={category}
                    onChange={(e) => setCategory(e.target.value as IssueCategory)}
                    className="w-full text-xs font-semibold rounded-xl border border-border-color p-2.5 bg-card-bg text-text-main focus:outline-none focus:ring-2 focus:ring-brand-500"
                  >
                    <option value="Pothole">Pothole</option>
                    <option value="Water Leakage">Water Leakage</option>
                    <option value="Broken Streetlight">Broken Streetlight</option>
                    <option value="Waste Management">Waste Management</option>
                    <option value="Infrastructure">Infrastructure</option>
                  </select>
                </div>

                <div>
                  <label className="block text-[10px] font-bold text-text-muted uppercase mb-1">AI Evaluated Severity</label>
                  <select
                    value={severity}
                    onChange={(e) => setSeverity(e.target.value as IssueSeverity)}
                    className="w-full text-xs font-semibold rounded-xl border border-border-color p-2.5 bg-card-bg text-text-main focus:outline-none focus:ring-2 focus:ring-brand-500"
                  >
                    <option value="Low">Low</option>
                    <option value="Medium">Medium</option>
                    <option value="High">High</option>
                    <option value="Critical">Critical</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-[10px] font-bold text-text-muted uppercase mb-1">Incident Report Title</label>
                <input
                  type="text"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  className="w-full text-xs font-semibold rounded-xl border border-border-color p-2.5 bg-card-bg text-text-main focus:outline-none focus:ring-2 focus:ring-brand-500"
                  placeholder="Enter a title for the issue"
                />
              </div>

              <div>
                <label className="block text-[10px] font-bold text-text-muted uppercase mb-1">Gemini Extracted Incident Summary</label>
                <textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  className="w-full text-xs font-medium rounded-xl border border-border-color p-2.5 bg-card-bg text-text-main h-20 focus:outline-none focus:ring-2 focus:ring-brand-500"
                  placeholder="Provide structured observations..."
                />
              </div>

              <div className="bg-amber-50 rounded-xl p-3.5 border border-amber-100 flex gap-2.5">
                <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" />
                <div>
                  <span className="block text-[10px] font-bold text-amber-900 uppercase">Gemini Real-Time Cautionary Advice</span>
                  <p className="text-[11px] text-amber-800 font-medium leading-relaxed mt-0.5">{aiCautionTips}</p>
                </div>
              </div>
            </div>
          )}

          {/* Location Fields */}
          <div className="space-y-3.5">
            <span className="block text-xs font-semibold text-text-main uppercase tracking-wider">Geographic Mapping Metadata</span>
            
            <div className="flex items-center gap-2">
              <div className="relative flex-1">
                <MapPin className="absolute left-3 top-3 text-text-muted w-4.5 h-4.5" />
                <input
                  type="text"
                  required
                  value={address}
                  onChange={(e) => setAddress(e.target.value)}
                  className="w-full pl-10 pr-4 py-2.5 text-xs font-medium rounded-xl border border-border-color bg-card-bg text-text-main focus:outline-none focus:ring-2 focus:ring-brand-500"
                  placeholder="Verify location street address..."
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-[10px] font-bold text-text-muted uppercase mb-1">GPS Latitude Coordinate</label>
                <input
                  type="number"
                  step="0.000001"
                  required
                  value={latitude}
                  onChange={(e) => setLatitude(Number(e.target.value))}
                  className="w-full text-xs font-mono rounded-xl border border-border-color p-2.5 bg-canvas-bg text-text-muted focus:outline-none"
                />
              </div>

              <div>
                <label className="block text-[10px] font-bold text-text-muted uppercase mb-1">GPS Longitude Coordinate</label>
                <input
                  type="number"
                  step="0.000001"
                  required
                  value={longitude}
                  onChange={(e) => setLongitude(Number(e.target.value))}
                  className="w-full text-xs font-mono rounded-xl border border-border-color p-2.5 bg-canvas-bg text-text-muted focus:outline-none"
                />
              </div>
            </div>
          </div>

          {/* Error Message */}
          {errorMessage && (
            <div className="p-3 bg-red-100 text-red-800 rounded-xl text-xs font-semibold flex items-center gap-2">
              <AlertTriangle className="w-4 h-4" />
              {errorMessage}
            </div>
          )}

          {/* Footer Action Buttons */}
          <div className="flex justify-end gap-3 pt-4 border-t border-border-color">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 text-xs font-bold text-text-muted hover:bg-card-hover rounded-xl transition-all"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isAnalyzing || !selectedImage}
              className="px-5 py-2 text-xs font-bold text-white bg-brand-600 hover:bg-brand-700 disabled:bg-slate-300 disabled:cursor-not-allowed rounded-xl transition-all shadow-md hover:shadow-lg shadow-brand-600/20 flex items-center gap-1.5"
            >
              Deploy Report to Map
            </button>
          </div>

        </form>
      </div>
    </div>
  );
}
